name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: dart:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: dart pub get
      - name: Build Runner
        run: dart run build_runner build
      - name: Analyze
        run: dart analyze
      - name: Run tests
        run: dart test
